title: DeadSirios
author: GitHub User
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Practice github pages website.

# social links
github_username: DeadSirios # DO NOT include the @ character, or else the build will fail!
twitter_username: BrewHeister # DO NOT include the @ character, or else the build will fail!
facebook_username: BrewHeister # DO NOT include the @ character, or else the build will fail!
instagram_username: BrewHeister # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
